# Generated by Django 4.2.16 on 2026-03-22 17:34

import blogapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_add_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover',
        ),
        migrations.CreateModel(
            name='BlogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=blogapp.models.blog_file_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='blogapp.blog')),
            ],
            options={
                'verbose_name': 'Blog file',
                'verbose_name_plural': 'Blog files',
            },
        ),
    ]
