# Generated by Django 4.2.16 on 2026-03-25 09:23

import blogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_title_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=blogapp.models.avatar_upload_path),
        ),
    ]
