# Generated by Django 4.2.16 on 2026-03-25 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0006_userprofile_add_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='blogapp.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog read',
                'verbose_name_plural': 'Blog reads',
                'unique_together': {('user', 'blog')},
            },
        ),
    ]
