# Generated by Django 4.2.16 on 2026-03-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_add_blog_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('emerald', 'Emerald'), ('ultramarine', 'Ultramarine'), ('violet', 'Violet & Orange')], default='emerald', max_length=32),
        ),
    ]
