# Generated by Django 4.2.16 on 2026-04-02 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0008_userprofile_add_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_in_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
